// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfxgZaFfoDrzWQH7tJh147hepfjJhaN-A',
    appId: '1:512484081225:web:09b29efe389a4ddae84998',
    messagingSenderId: '512484081225',
    projectId: 'coworking-space-b2975',
    authDomain: 'coworking-space-b2975.firebaseapp.com',
    storageBucket: 'coworking-space-b2975.appspot.com',
    measurementId: 'G-S3Y6ZSDMN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGx9SJNYZwnbc3zQMY3Ld6eHE3fj8C_yY',
    appId: '1:512484081225:android:52e6108d13e2940ee84998',
    messagingSenderId: '512484081225',
    projectId: 'coworking-space-b2975',
    storageBucket: 'coworking-space-b2975.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_1nz-0RxW45KqDlUFAqdQYbXrlcc9744',
    appId: '1:512484081225:ios:2e1d63cfdf11c9b7e84998',
    messagingSenderId: '512484081225',
    projectId: 'coworking-space-b2975',
    storageBucket: 'coworking-space-b2975.appspot.com',
    iosClientId: '512484081225-nes4t2r7a1dmhd97ujttrpsllq1tc3g6.apps.googleusercontent.com',
    iosBundleId: 'com.islamimamitiproject.coworkingspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_1nz-0RxW45KqDlUFAqdQYbXrlcc9744',
    appId: '1:512484081225:ios:f1ebf7a684df7ad5e84998',
    messagingSenderId: '512484081225',
    projectId: 'coworking-space-b2975',
    storageBucket: 'coworking-space-b2975.appspot.com',
    iosClientId: '512484081225-h7cekbraa8kvainqoqmph3g630ekp8ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.coworkingspace',
  );
}
